server:
  port: 10010 #服务端口
spring:
  application:
    name: gateway #指定服务名
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api
  routes:
    user-service: # 这里是路由id，随意写
      path: /user/** # 这里是映射路径
      serviceId: user-service # 指定服务名称
      strip-prefix: false
  ignored-services: #忽略指定的服务不想对外暴露
    - consumer-service
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:2000
ribbon:
  ConnectTimeout: 500 # 连接超时时间(ms)
  ReadTimeout: 4000 # 通信超时时间(ms)
